/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;
import clases.*;
import javax.swing.JOptionPane;
/**
 *
 * @author USUARIO
 */
public class principaltest extends javax.swing.JPanel {

    /**
     * Creates new form principal
     */
    public principaltest() {
        initComponents();
        txtEnteroUno.requestFocusInWindow();
        cmdCalcular.setEnabled(true);
        cmdFraccionario.setEnabled(false);
        cmdLimpiar.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtEnteroUno = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtNumeradorUno = new javax.swing.JTextField();
        txtDenominadorUno = new javax.swing.JTextField();
        cmbOperacion = new javax.swing.JComboBox<>();
        txtEnteroDos = new javax.swing.JTextField();
        txtNumeradorDos = new javax.swing.JTextField();
        txtDenominadorDos = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtEnteroTres = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        txtNumeradorTres = new javax.swing.JTextField();
        txtDenominadorTres = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        txtNumeradorCuatro = new javax.swing.JTextField();
        txtDenominadorCuatro = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        cmdCalcular = new javax.swing.JButton();
        cmdFraccionario = new javax.swing.JButton();
        cmdLimpiar = new javax.swing.JButton();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("OPERACIONES CON NÚMEROS MIXTOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));
        jPanel1.add(txtEnteroUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 30, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 60, 10));
        jPanel1.add(txtNumeradorUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 60, -1));
        jPanel1.add(txtDenominadorUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 60, -1));

        cmbOperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Suma", "Resta", "Multiplicación", "División" }));
        jPanel1.add(cmbOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));
        jPanel1.add(txtEnteroDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 30, -1));
        jPanel1.add(txtNumeradorDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 60, -1));
        jPanel1.add(txtDenominadorDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 60, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 60, 10));

        jLabel2.setText("=");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, -1));

        txtEnteroTres.setEditable(false);
        jPanel1.add(txtEnteroTres, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 30, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 60, 10));

        txtNumeradorTres.setEditable(false);
        jPanel1.add(txtNumeradorTres, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 60, -1));

        txtDenominadorTres.setEditable(false);
        jPanel1.add(txtDenominadorTres, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 60, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fraccionario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNumeradorCuatro.setEditable(false);
        jPanel2.add(txtNumeradorCuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 60, -1));

        txtDenominadorCuatro.setEditable(false);
        jPanel2.add(txtDenominadorCuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 60, -1));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 60, 10));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 120, 120));

        cmdCalcular.setText("Calcular");
        cmdCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(cmdCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));

        cmdFraccionario.setText("Fraccionario");
        cmdFraccionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdFraccionarioActionPerformed(evt);
            }
        });
        jPanel1.add(cmdFraccionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));

        cmdLimpiar.setText("Limpiar");
        cmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCalcularActionPerformed

        int op, n1 = 0, n2 = 0, ente1 = 1, ente2 = 1, d1 = 1, d2 = 1, sw = 1;
        Mixto f1,f2,f3;
        op = cmbOperacion.getSelectedIndex();
        
        if (txtEnteroUno.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el primer número entero", "Error", JOptionPane.ERROR_MESSAGE);
            txtEnteroUno.requestFocusInWindow();
            sw = 0;              
        }else if(txtNumeradorUno.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el primer numerador", "Error", JOptionPane.ERROR_MESSAGE);
            txtNumeradorUno.requestFocusInWindow();
            sw = 0;
        }else if (txtDenominadorUno.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Ingrese el primer denominador", "Error", JOptionPane.ERROR_MESSAGE);
            txtDenominadorUno.requestFocusInWindow();
            sw = 0;   
        }else if (txtEnteroDos.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Ingrese el segundo número entero", "Error", JOptionPane.ERROR_MESSAGE);
            txtEnteroDos.requestFocusInWindow();
            sw = 0;    
        }else if (txtNumeradorDos.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Ingrese el segundo numerador", "Error", JOptionPane.ERROR_MESSAGE);
            txtNumeradorDos.requestFocusInWindow();
            sw = 0;
        }else if (txtDenominadorDos.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Ingrese el segundo denominador", "Error", JOptionPane.ERROR_MESSAGE);
            txtDenominadorDos.requestFocusInWindow();
            sw = 0;
        }else{
            try{
               ente1 = Integer.parseInt(txtEnteroUno.getText()); 
            }catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "El primer número entero debe ser un número válido", "Error", JOptionPane.ERROR_MESSAGE);
                txtEnteroUno.requestFocusInWindow();
                txtEnteroUno.selectAll();
                sw = 0;
        }
            try{
               n1 = Integer.parseInt(txtNumeradorUno.getText()); 
            }catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "El primer numerador debe ser un número válido", "Error", JOptionPane.ERROR_MESSAGE);
                txtNumeradorUno.requestFocusInWindow();
                txtNumeradorUno.selectAll();
                sw = 0;
        }
            try{
               d1 = Integer.parseInt(txtDenominadorUno.getText());   
            }catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "El primer denominador debe ser un número válido", "Error", JOptionPane.ERROR_MESSAGE);
                txtDenominadorUno.requestFocusInWindow();
                sw = 0;
                if (d1 > n1){
            JOptionPane.showMessageDialog(this, "El denominador no puede ser un número mayor que el numerador", "error", JOptionPane.ERROR_MESSAGE);
                txtDenominadorUno.requestFocusInWindow();
                txtDenominadorUno.selectAll();
                sw = 0;
                }
        }        
            try{
               ente2 = Integer.parseInt(txtEnteroDos.getText()); 
            }catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "El segundo número entero debe ser un número válido", "Error", JOptionPane.ERROR_MESSAGE);
                txtEnteroDos.requestFocusInWindow();
                txtEnteroDos.selectAll();
                sw = 0;
        }        
            try{
               n2 = Integer.parseInt(txtNumeradorDos.getText()); 
            }catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "El segundo numerador debe ser un número válido", "Error", JOptionPane.ERROR_MESSAGE);
                txtNumeradorDos.requestFocusInWindow();
                txtNumeradorDos.selectAll();
                sw = 0;
        }
            try{
                d2 = Integer.parseInt(txtDenominadorDos.getText());
            }catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "El segundo denominador debe ser un número válido", "Error", JOptionPane.ERROR_MESSAGE);
                txtDenominadorDos.requestFocusInWindow();
                txtDenominadorDos.selectAll();
                sw = 0;
                if (d2 > n2){
            JOptionPane.showMessageDialog(this, "El denominador no puede ser un número mayor que el numerador", "error", JOptionPane.ERROR_MESSAGE);
                txtDenominadorDos.requestFocusInWindow();
                txtDenominadorDos.selectAll();
                sw = 0;
                }
        } 
        
        try{
        f1 = new Mixto(n1,d1,ente1);
        f2 = new Mixto(n2,d2,ente2);
        
        switch(op){
            
            case 0:
                f3 = f1.suma(f2);
                txtEnteroTres.setText(""+f3.getEntero());
                txtNumeradorTres.setText(""+f3.getNumerador());
                txtDenominadorTres.setText(""+f3.getDenominador());
            break; 
            
            case 1: 
                f3 = f1.resta(f2);
                txtEnteroTres.setText(""+f3.getEntero());
                txtNumeradorTres.setText(""+f3.getNumerador());
                txtDenominadorTres.setText(""+f3.getDenominador());
            break;
            
            case 2: 
                f3 = f1.multiplicacion(f2);
                txtEnteroTres.setText(""+f3.getEntero());
                txtNumeradorTres.setText(""+f3.getNumerador());
                txtDenominadorTres.setText(""+f3.getDenominador());
            break;
            
            case 3:
                f3 = f1.division(f2);
                txtEnteroTres.setText(""+f3.getEntero());
                txtNumeradorTres.setText(""+f3.getNumerador());
                txtDenominadorTres.setText(""+f3.getDenominador());
            break;       
        }
        
        } catch (DenominadorCeroException e){
        Helper.mensaje(null, "No puede digitar 0 de denominador","Error",2);
        }    
       cmdCalcular.setEnabled(true);
       cmdFraccionario.setEnabled(true);
       cmdLimpiar.setEnabled(true);
    }//GEN-LAST:event_cmdCalcularActionPerformed
}
    private void cmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarActionPerformed

        txtNumeradorUno.setText("");
        txtNumeradorDos.setText("");
        txtNumeradorTres.setText("");
        txtDenominadorUno.setText("");
        txtDenominadorDos.setText("");
        txtDenominadorTres.setText("");
        txtNumeradorCuatro.setText("");
        txtDenominadorCuatro.setText("");
        txtEnteroUno.setText("");
        txtEnteroDos.setText("");
        txtEnteroTres.setText("");
        txtEnteroUno.requestFocusInWindow();
        cmbOperacion.setSelectedIndex(0);
        cmdCalcular.setEnabled(true);
        cmdFraccionario.setEnabled(false);
        cmdLimpiar.setEnabled(true);
    
    }//GEN-LAST:event_cmdLimpiarActionPerformed

    private void cmdFraccionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdFraccionarioActionPerformed
        // TODO add your handling code here:
        int num4, den4, frac, ente4, n4parcial;  
        String n4, d4;
        
        ente4 = Integer.parseInt(txtEnteroTres.getText());
        num4 = Integer.parseInt(txtNumeradorTres.getText());
        den4 = Integer.parseInt(txtDenominadorTres.getText());
        
        frac = (ente4 * den4) + num4;
        n4 = String.valueOf(frac);
            txtNumeradorCuatro.setText(n4);
            
        d4 = String.valueOf(den4);
            txtDenominadorCuatro.setText(d4);
            
        cmdCalcular.setEnabled(false);
        cmdFraccionario.setEnabled(true);
        cmdLimpiar.setEnabled(true);
    }//GEN-LAST:event_cmdFraccionarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbOperacion;
    private javax.swing.JButton cmdCalcular;
    private javax.swing.JButton cmdFraccionario;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField txtDenominadorCuatro;
    private javax.swing.JTextField txtDenominadorDos;
    private javax.swing.JTextField txtDenominadorTres;
    private javax.swing.JTextField txtDenominadorUno;
    private javax.swing.JTextField txtEnteroDos;
    private javax.swing.JTextField txtEnteroTres;
    private javax.swing.JTextField txtEnteroUno;
    private javax.swing.JTextField txtNumeradorCuatro;
    private javax.swing.JTextField txtNumeradorDos;
    private javax.swing.JTextField txtNumeradorTres;
    private javax.swing.JTextField txtNumeradorUno;
    // End of variables declaration//GEN-END:variables
}
